name: skibidi_roast
description: "SkibidiRoast ğŸ˜ğŸ”¥ is a fun app where users upload images ğŸ“¸ and get instant, AI-generated roasts ğŸ¤–ğŸ’¥. Itâ€™s a fun, interactive way to see witty, playful burns ğŸ˜ğŸ”¥ tailored to your photos, giving users a hilarious ğŸ˜‚ and shareable ğŸ¤³ experience."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  image_picker: ^1.2.1
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.4
  http: ^1.6.0
  mime: ^2.0.0
  equatable: ^2.0.7
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.4
  built_value_generator: ^8.5.0
  freezed: ^2.4.5
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FBF3F0"
  image: assets/icons/splash_icon.png
  android: true
  android_gravity: center
  ios: true
  android_12:
    color: "#FBF3F0"
    image: assets/icons/splash_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/

  
